spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
jwt:
  secret: 5e2c1a30dd914bd7ad8035fc647d0141
  expiration: 3600000

custom:
  login: adm
  senha: adm
